[build-system]
requires = ["setuptools>=70.1", "cffi>=1.17.1", "meson", "ninja", "mako", "pyyaml"]
build-backend = "setuptools.build_meta"

[project]
name = "comma-deps-raylib"
version = "6.0.0.1"
description = "raylib + pyray Python bindings (commaai fork)"
requires-python = ">=3.12"
dependencies = ["cffi>=1.17.1"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["raylib", "pyray"]
namespaces = false

[tool.setuptools.package-data]
raylib = ["_raylib_cffi*.so", "install/include/*.h", "install/lib/*.a", "install/lib/*.so*"]
