[build-system]
requires = ["setuptools>=64", "wheel", "pip", "cffi"]
build-backend = "setuptools.build_meta"

[project]
name = "raylib"
version = "5.5.0.4"
description = "Python bindings for raylib graphics library (CFFI)"
requires-python = ">=3.8"
dependencies = ["cffi>=1.15.1"]

[tool.setuptools.packages.find]
include = ["raylib*"]

[tool.setuptools.package-data]
raylib = ["install/**/*"]
