name: manylinux image

on:
  push:
    branches: [master, fast]
    paths: ['manylinux/Dockerfile']
  workflow_dispatch:

jobs:
  build:
    name: manylinux (${{ matrix.arch }})
    runs-on: ${{ matrix.runs-on }}
    permissions:
      packages: write
    strategy:
      matrix:
        include:
          - arch: x86_64
            runs-on: ubuntu-latest
          - arch: aarch64
            runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: manylinux
          build-args: ARCH=${{ matrix.arch }}
          push: true
          tags: ghcr.io/${{ github.repository }}/manylinux:${{ matrix.arch }}
